backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  repo: FacundoBrum16/virromar

media_folder: static/img
public_folder: /img

collections:
  - name: "Works"
    label: "works"
    folder: "content/works"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Categoria", name: "tag", widget: "string" }
      - {
          label: "Foto",
          name: "photo",
          widget: "image",
          default: "/img/default.jpg",
        }
